# render.yaml
# IMPORTANT: This file defines the configuration for the Render service
# Any build commands set in the Render dashboard will override these settings
services:
  - type: web # Specifies this is a web service
    name: exact-transcriber # Choose a name for your service (same as in Render UI)
    env: python # Specifies the runtime environment
    plan: free # Specifies the instance type
    runtime: python3
    # IMPORTANT: This build command must match what's set in the Render dashboard
    buildCommand: ./render-build.sh
    startCommand: "streamlit run main.py --server.port $PORT --server.address 0.0.0.0 --server.headless true"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      # Required for Streamlit to work correctly
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
    healthCheckPath: "/_stcore/health"
    buildFilter:
      paths:
        - .render-buildpacks.txt
        - Aptfile
        - pyproject.toml
        - runtime.txt
        - render-build.sh
        - main.py
        - "*.py"
        - Procfile
